# Generated by Django 6.0.4 on 2026-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaofacil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Breve descrição do investimento', max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_aplicacao', models.DateField(verbose_name='Data de aplicação')),
                ('tipo', models.CharField(choices=[('renda_fixa', 'Renda Fixa'), ('renda_variavel', 'Renda Variável')], max_length=15, verbose_name='Tipo')),
                ('cotas', models.PositiveIntegerField(blank=True, help_text='Informe somente para investimentos em renda variável', null=True, verbose_name='Número de cotas')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-data_aplicacao'],
            },
        ),
    ]
