# Generated by Django 6.0.4 on 2026-05-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaofacil', '0002_investimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria/tag para despesas', max_length=50, unique=True, verbose_name='Nome da Tag')),
                ('cor', models.CharField(default='#6c757d', help_text='Cor hexadecimal para identificação visual', max_length=7, verbose_name='Cor')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da categoria', verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Se a tag está ativa para uso', verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Categoria da despesa (apenas para despesas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaofacil.tag', verbose_name='Tag/Categoria'),
        ),
    ]
